export const ADD_BUN_TO_BURGER = 'ADD_BUN_TO_BURGER';
export const ADD_INGREDIENT_TO_BURGER = 'ADD_INGREDIENT_TO_BURGER';
export const CLEAR_BURGER = 'CLEAR_BURGER';
export const DEL_INGREDIENT_FROM_BURGER = 'DEL_INGREDIENT_FROM_BURGER';
export const SORT_INGREDIENTS_IN_BURGER = 'SORT_INGREDIENTS_IN_BURGER';
